export const INITIAL_SEEDS = [
  // --- FUN (Card Games) ---
  { id: 'fun-rummy', topic: 'fun', title: 'How to Play Rummy', body: 'Standard Deck. 2-6 Players.\n\nOBJECTIVE: Form sets (3-4 of a kind) or runs (3+ consecutive same suit).\n\nDEAL: 10 cards (2 players), 7 cards (3-4 players).\n\nPLAY: Draw from stock or discard pile. Meld valid sets. Discard one card. Round ends when a player empties hand.' },
  { id: 'fun-poker', topic: 'fun', title: 'Texas Hold\'em Basics', body: 'OBJECTIVE: Best 5-card hand.\n\nTHE FLOP: 3 community cards dealt face up.\nTHE TURN: 4th community card.\nTHE RIVER: 5th community card.\n\nRANKINGS:\nHigh Card > Pair > Two Pair > 3-of-a-Kind > Straight > Flush > Full House > Quads > Straight Flush > Royal Flush.' },
  { id: 'fun-blackjack', topic: 'fun', title: 'Blackjack Strategy', body: 'OBJECTIVE: Beat dealer without exceeding 21.\n\nBASIC RULES:\n- Hit on soft 17.\n- Double down on 11.\n- Split Aces and 8s.\n- Never split 10s or 5s.\n- Dealer must hit until 17.' },
  { id: 'fun-crazy8', topic: 'fun', title: 'Crazy Eights', body: 'OBJECTIVE: Be the first to empty your hand.\n\nRULES:\n- Match rank or suit of top discard.\n- Eights are wild (change suit).\n- Draw if you cannot play.\n- 2 Players: Deal 7 cards. 3+ Players: Deal 5 cards.' },
  { id: 'fun-solitaire', topic: 'fun', title: 'Klondike Solitaire', body: 'OBJECTIVE: Build 4 foundation piles (Ace to King) by suit.\n\nTABLEAU: Build down in alternating colors (Red 7 on Black 8).\nSTOCK: Draw 1 or 3 cards at a time. Only Kings can fill empty columns.' },
  // --- PRO (Professional) ---
  { id: 'pro-jobs', topic: 'pro', title: 'Job Search Guide', body: '1. LinkedIn: Optimize headline, turn on "Open to Work" (Recruiter only).\n2. Indeed/Glassdoor: Good for salary comparisons.\n3. AngelList: Best for startup jobs.\n4. Network: 80% of jobs are not posted. Message peers directly.' },
  { id: 'pro-skills', topic: 'pro', title: 'Soft vs. Hard Skills', body: 'HARD SKILLS (Get you the interview):\n- Coding, Accounting, Machine Operation, Language proficiency.\n\nSOFT SKILLS (Get you the job/promo):\n- Communication, Adaptability, Conflict Resolution, Time Management.\n\nTip: Hard skills expire fast. Soft skills compound.' },
  { id: 'pro-social', topic: 'pro', title: 'LinkedIn Protocol', body: 'The "Professional" Social Network.\n1. Photo: Professional lighting, smile.\n2. Headline: Value prop, not just job title (e.g., "Helping teams build X" vs "Manager").\n3. Activity: Commenting > Posting. Add value to other peoples posts to gain visibility.' },
  { id: 'pro-learn', topic: 'pro', title: 'Continuous Learning', body: 'The ability to learn is the only future-proof skill.\n\nRESOURCES:\n- Coursera/EdX (University level)\n- Udemy (Skill specific)\n- YouTube (How-to)\n- Khan Academy (Foundational)\n\n"Live as if you were to die tomorrow. Learn as if you were to live forever." - Gandhi' },
  // --- FIT (Fitness) ---
  { id: 'fit-cals', topic: 'fit', title: 'Calorie Calculator', body: 'BMR (Basal Metabolic Rate): Calories burned doing nothing.\n\nRough Estimate:\nWeight (lbs) x 10 = Coma Calories.\nWeight x 13 = Sedentary.\nWeight x 15 = Moderate Activity.\nWeight x 18 = Athlete.\n\nTo lose weight: Eat 500 less than your number.' },
  { id: 'fit-hiit', topic: 'fit', title: 'Beginner HIIT', body: 'High Intensity Interval Training.\n\nCIRCUIT (Repeat 3x):\n1. Jumping Jacks (45s)\n2. Rest (15s)\n3. Bodyweight Squats (45s)\n4. Rest (15s)\n5. Pushups (or knees) (45s)\n6. Rest (15s)\n7. Plank (45s)' },
  { id: 'fit-hr', topic: 'fit', title: 'Target Heart Rate', body: 'Max HR = 220 - Your Age.\n\nZONES:\n- Fat Burn: 60-70% of Max.\n- Cardio: 70-80% of Max.\n- Peak: 80-90% of Max.\n\nMeasure: Count beats for 10s, multiply by 6.' },
  { id: 'fit-water', topic: 'fit', title: 'Hydration Math', body: 'Baseline: Half your body weight in ounces per day.\n\nExample: 200lbs person = 100oz water.\n\nAdd 12oz for every 30 mins of exercise.\nSigns of Dehydration: Fatigue, headache, dark urine.' },
  { id: 'fit-stretch', topic: 'fit', title: 'Circulation & Stretch', body: 'Do this every morning:\n1. Neck Rolls (30s)\n2. Shoulder Shrugs (30s)\n3. Forward Fold (Reach for toes, hold 30s)\n4. Cat-Cow Yoga Pose (1 min)\n5. Calf Stretch against wall.' },
  // --- EDU (Education & The Source) ---
  { id: 'edu-method', topic: 'edu', title: 'The Scientific Method', body: '1. Observe: See a phenomenon.\n2. Question: Ask "Why?"\n3. Hypothesize: Make a prediction.\n4. Test: Design an experiment.\n5. Analyze: Data vs Prediction.\n6. Conclude: Update Hypothesis.\n\nScience is a process, not a belief system.' },
  { id: 'edu-bias', topic: 'edu', title: 'What is Bias?', body: 'Bias is a shortcut your brain takes.\n\nCONFIRMATION BIAS: Ignoring facts that contradict your belief.\nSURVIVORSHIP BIAS: Focusing on winners and ignoring losers (e.g., "Steve Jobs dropped out, so I should too").\nANCHORING: Relying too heavily on the first piece of info offered.' },
  { id: 'edu-hist', topic: 'edu', title: 'History Basics', body: 'Primary Source: Written at the time (Diary, Law, Photo).\nSecondary Source: Written after (Textbook, Biography).\n\n"History is written by the victors." Always check who wrote the account and why.' },
  { id: 'edu-econ', topic: 'edu', title: 'Economics 101', body: 'SCARCITY: Unlimited wants, limited resources.\nSUPPLY & DEMAND: Price settles where these curves meet.\nOPPORTUNITY COST: The value of the next best alternative you gave up to do this.\nINFLATION: Too much money chasing too few goods.' },
  { id: 'edu-pol', topic: 'edu', title: 'Politics Basics', body: 'LEFT (Liberal): Government solves problems, equality focus, regulation.\nRIGHT (Conservative): Individual solves problems, liberty focus, deregulation.\nCENTER: Mix of both.\n\nPolitics is the distribution of power and resources.' },
  { id: 'edu-journo', topic: 'edu', title: 'Journalism Standards', body: '1. Verification: Check facts with 2 sources.\n2. Independence: Not paid by the subject.\n3. Accountability: Admit errors.\n\nOpinion vs News: News says "It rained." Opinion says "The rain is bad."' },
  { id: 'edu-net', topic: 'edu', title: 'How Internet Works', body: 'IP Address: The GPS location of a computer.\nDNS: The Phonebook (turns google.com into 142.250...). \nPacket: Data chopped into tiny envelopes.\nRouter: The traffic cop directing envelopes.\nServer: The computer that holds the file you want.' },
  // --- THE SOURCE LORE ---
  { id: 'src-diff', topic: 'edu', title: 'The Source: Our Mission', body: 'We connect people, not servers. No algorithm feeds you; you choose what to consume. We are building the Human Web.' },
  { id: 'src-sov', topic: 'edu', title: 'The Source: Sovereign Data', body: 'Your data lives on your device. You own the keys. No cloud backup means no cloud leaks. If you lose your phone, you lose your data. That is the price of freedom.' },
  { id: 'src-use', topic: 'edu', title: 'The Source: Use Case', body: 'Why share in person? High bandwidth trust. You know who you are talking to because they are standing in front of you. It is the only un-fakeable connection.' },
  { id: 'src-edge', topic: 'edu', title: 'The Source: Edge Computing', body: 'The Cloud is just someone else\'s computer. Edge computing means the work happens in your hand, on your battery, using your processor. We reduce the reliance on Big Tech server farms.' },
  { id: 'src-bots', topic: 'edu', title: 'The Source: Bot Farms', body: 'Bots cannot physically shake hands. By relying on Bluetooth proximity, we eliminate 99% of AI spam and fake accounts. If you didn\'t stand near them, they don\'t exist.' },
  { id: 'src-crypto', topic: 'edu', title: 'The Source: Handshake', body: 'The Cryptographic Handshake. When devices touch, they exchange public keys. Math proves the connection occurred. Trust is established mathematically, then verified socially.' },
  { id: 'src-trust', topic: 'edu', title: 'The Source: Trust Algo', body: 'The Human Trust Algorithm. Trust is not a boolean (Yes/No). It is a gradient. It is earned by proximity, repetition, and verification. We map this gradient.' },
  // --- FOOD (Recipes) ---
  { id: 'food-omelet', topic: 'food', title: 'Classic Omelet', body: 'Ingredients: 3 Eggs, 1tbsp Butter, Salt/Pepper, Cheese.\n\n1. Whisk eggs with salt/pepper.\n2. Heat butter in non-stick pan (Med-High).\n3. Pour eggs. Tilt pan to spread.\n4. Lift edges to let raw egg run under.\n5. Add cheese. Fold in half. Slide onto plate.' },
  { id: 'food-stirfry', topic: 'food', title: 'Chicken Stir Fry', body: 'Ing: Chicken breast (cubed), Broccoli, Soy Sauce, Garlic, Oil.\n\n1. High heat wok/pan with oil.\n2. Sear chicken (3-4 mins). Remove.\n3. Add veggies + garlic (2 mins).\n4. Return chicken. Add soy sauce.\n5. Toss 1 min. Serve over rice.' },
  { id: 'food-pasta', topic: 'food', title: 'Aglio e Olio', body: 'Ing: Spaghetti, Olive Oil (lots), Garlic (sliced), Red Pepper Flakes, Parsley.\n\n1. Boil pasta (salt water).\n2. Sauté garlic/flakes in oil (low heat, do not burn).\n3. Add cooked pasta + splash of pasta water to oil.\n4. Toss vigorously to emulsify sauce.\n5. Top with parsley.' },
  { id: 'food-avo', topic: 'food', title: 'Avocado Toast', body: 'Ing: Sourdough Bread, Ripe Avocado, Lemon, Salt, Chili Flakes.\n\n1. Toast bread well.\n2. Mash avocado with lemon juice + salt.\n3. Spread thick on toast.\n4. Top with flakes (and poached egg if fancy).' },
  { id: 'food-salad', topic: 'food', title: 'Greek Salad', body: 'Ing: Cucumber, Tomato, Red Onion, Feta, Olives, Oregano, Olive Oil.\n\n1. Chop veggies chunky.\n2. Combine in bowl.\n3. Top with block of Feta.\n4. Drizzle oil and sprinkle oregano. No lettuce required.' },
  { id: 'food-tacos', topic: 'food', title: 'Basic Beef Tacos', body: 'Ing: Ground Beef, Taco Seasoning, Tortillas, Lettuce, Cheese.\n\n1. Brown beef in skillet.\n2. Drain fat.\n3. Add seasoning + splash water. Simmer 3 mins.\n4. Warm tortillas.\n5. Assemble.' },
  { id: 'food-smoothie', topic: 'food', title: 'Green Smoothie', body: 'Ing: Spinach (handful), Banana (frozen), Apple, Water/Milk.\n\n1. Blend spinach + liquid first (no chunks).\n2. Add fruit.\n3. Blend until smooth.\n4. Drink immediately.' },
  { id: 'food-rice', topic: 'food', title: 'Perfect Rice', body: 'Ratio: 1 cup Rice : 1.5 cups Water.\n\n1. Rinse rice until water runs clear.\n2. Combine water/rice/salt in pot.\n3. Boil. Cover. REDUCE heat to Low.\n4. Simmer 18 mins (Do not peek).\n5. Remove from heat. Rest 5 mins. Fluff with fork.' },
  { id: 'food-chili', topic: 'food', title: 'Easy Chili', body: 'Ing: Ground Beef, Kidney Beans, Diced Tomatoes, Chili Powder, Onion.\n\n1. Brown beef + onion.\n2. Add canned beans (rinsed) + tomatoes (undrained).\n3. Add 2 tbsp Chili Powder.\n4. Simmer 20 mins.' },
  { id: 'food-pancakes', topic: 'food', title: 'Simple Pancakes', body: 'Ing: 1c Flour, 2tbsp Sugar, 2tsp Baking Powder, 1 Egg, 1c Milk.\n\n1. Mix dry ingredients.\n2. Whisk egg/milk. Combine.\n3. Butter hot pan.\n4. Pour batter.\n5. Flip when bubbles pop and stay open.' }
];